import { createStyles } from '../../theme/hooks/useStyles.hook';

export const stylesheet = createStyles((theme) => ({
  modal: {
    flex: 1,
    alignItems: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  popup: {
    textAlign: 'center',
    alignItems: 'center',
    width: '35%',
    height: '40%',
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.borderColor,
    marginBottom: '13%',
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontFamily: theme.fonts.bold,
    marginTop: 18,
    marginLeft: 20,
    marginBottom: 25,
    color: theme.colors.text,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: theme.colors.borderColor,
    borderRadius: 5,
    width: '80%',
  },

  buttonContainerModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginTop: '35%',
    marginBottom: 18,
  },
  buttonCancelContent: {
    width: 110,
    height: 38,
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 10,
    paddingBottom: 10,
    borderWidth: 1,
    borderEndEndRadius: 5,
    borderColor: theme.colors.borderColorButton,
    backgroundColor: theme.colors.background,
  },
  buttonCancelTitle: {
    fontSize: 18,
    color: theme.colors.buttonText,
    fontFamily: theme.fonts.regular,
  },
  buttonApllyContent: {
    width: 110,
    height: 38,
    paddingLeft: 22,
    paddingRight: 22,
    paddingTop: 10,
    paddingBottom: 10,
    borderWidth: 1,
    borderEndEndRadius: 5,
    borderColor: '#6C63FF',
    backgroundColor: '#6C63FF',
  },
  buttonApllyTitle: {
    fontSize: 18,
    color: '#F7F7F7',
    fontFamily: theme.fonts.regular,
  },
}));
