import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    //flex: 1,
    //justifyContent: 'center',
    //alignItems: 'center',
    //backgroundColor: 'green',
    //width: '96%',
    //height: '90%',
    //marginLeft: '2%',
    //borderWidth: 2,
    // borderRadius: 5,
  },

  headerList: {
    //backgroundColor: "blue",
    width: '96%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '8%',
    borderWidth: 2,
    borderRadius: 5,
    marginLeft: '2%',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  inputContainer: {
    //flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '5%',
    //backgroundColor: 'red',
    height: 70,
    margin: 10,
  },
  buttonContainer: {
    //width: 50,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    //backgroundColor: 'green',
    marginLeft: 'auto',
    //marginBottom: 'auto',
  },
  input: {
    borderWidth: 2,
    width: '75%',
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    //backgroundColor: 'red',
  },
  button: {
    width: 50,
    height: 23,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 2,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    //backgroundColor: "#007AFF",
    margin: 5,
  },
  textConteiner: {
    flexDirection: 'row',
    padding: 20,
    margin: 5,
    borderWidth: 2,
    width: '95%',
    height: 65,
    borderRadius: 5,
  },
  text: {
    width: '70%',
  },
});
